/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.zamcan.madrassa;

public final class R {
  public static final class color {
    /**
     * EduNoor Visual v3 — Parchment / Walnut / Clay / Gold
     */
    public static final int edunoor_background=0x7f010000;
    public static final int edunoor_border=0x7f010001;
    public static final int edunoor_clay=0x7f010002;
    public static final int edunoor_clay_dark=0x7f010003;
    public static final int edunoor_clay_soft=0x7f010004;
    public static final int edunoor_dusty_blue=0x7f010005;
    public static final int edunoor_gold=0x7f010006;
    public static final int edunoor_gold_soft=0x7f010007;
    public static final int edunoor_ink=0x7f010008;
    public static final int edunoor_ink_soft=0x7f010009;
    public static final int edunoor_muted=0x7f01000a;
    public static final int edunoor_pattern=0x7f01000b;
    public static final int edunoor_surface=0x7f01000c;
    public static final int edunoor_surface_warm=0x7f01000d;
    public static final int edunoor_teal=0x7f01000e;
    public static final int edunoor_walnut=0x7f01000f;
    public static final int edunoor_white=0x7f010010;
  }
  public static final class dimen {
    public static final int bismillah_height=0x7f020000;
    public static final int bottom_bar_height=0x7f020001;
    public static final int card_radius=0x7f020002;
    public static final int divider_height=0x7f020003;
    public static final int divider_width=0x7f020004;
    public static final int header_height=0x7f020005;
    public static final int hero_title_height=0x7f020006;
    public static final int hero_top_gap=0x7f020007;
    public static final int mark_size=0x7f020008;
    /**
     * Visual V4 spacing system
     */
    public static final int page_padding=0x7f020009;
    public static final int role_area_gap=0x7f02000a;
    public static final int role_card_gap=0x7f02000b;
    public static final int role_card_height=0x7f02000c;
    public static final int tagline_height=0x7f02000d;
  }
  public static final class drawable {
    public static final int edunoor_arch=0x7f030000;
    public static final int edunoor_background=0x7f030001;
    public static final int edunoor_canvas=0x7f030002;
    public static final int edunoor_header=0x7f030003;
    public static final int edunoor_icon=0x7f030004;
    public static final int edunoor_mark=0x7f030005;
    public static final int parent_card=0x7f030006;
    public static final int ustadh_card=0x7f030007;
  }
  public static final class string {
    public static final int app_name=0x7f040000;
    public static final int brand_subtitle=0x7f040001;
    public static final int brand_title=0x7f040002;
    public static final int greeting=0x7f040003;
    public static final int help=0x7f040004;
    public static final int hero_description=0x7f040005;
    public static final int hero_title=0x7f040006;
    public static final int language=0x7f040007;
    public static final int parent_action=0x7f040008;
    public static final int parent_subtitle=0x7f040009;
    public static final int parent_title=0x7f04000a;
    public static final int privacy=0x7f04000b;
    public static final int terms=0x7f04000c;
    public static final int ustadh_action=0x7f04000d;
    public static final int ustadh_subtitle=0x7f04000e;
    public static final int ustadh_title=0x7f04000f;
  }
  public static final class style {
    public static final int AppTheme=0x7f050000;
  }
}